# Form implementation generated from reading ui file 'hd.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialogHdBackup(object):
    def setupUi(self, dialogHdBackup):
        dialogHdBackup.setObjectName("dialogHdBackup")
        dialogHdBackup.resize(600, 400)
        self.gridLayout = QtWidgets.QGridLayout(dialogHdBackup)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.labelMnemonic = QtWidgets.QLabel(dialogHdBackup)
        self.labelMnemonic.setObjectName("labelMnemonic")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelMnemonic)
        self.plainTextEditMnemonic = QtWidgets.QPlainTextEdit(dialogHdBackup)
        self.plainTextEditMnemonic.setReadOnly(True)
        self.plainTextEditMnemonic.setObjectName("plainTextEditMnemonic")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.plainTextEditMnemonic)
        self.labelPath = QtWidgets.QLabel(dialogHdBackup)
        self.labelPath.setObjectName("labelPath")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelPath)
        self.lineEditPath = QtWidgets.QLineEdit(dialogHdBackup)
        self.lineEditPath.setText("")
        self.lineEditPath.setReadOnly(True)
        self.lineEditPath.setObjectName("lineEditPath")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditPath)
        self.labelPassphrase = QtWidgets.QLabel(dialogHdBackup)
        self.labelPassphrase.setObjectName("labelPassphrase")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelPassphrase)
        self.lineEditPassphrase = QtWidgets.QLineEdit(dialogHdBackup)
        self.lineEditPassphrase.setReadOnly(True)
        self.lineEditPassphrase.setObjectName("lineEditPassphrase")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditPassphrase)
        self.labelXprv = QtWidgets.QLabel(dialogHdBackup)
        self.labelXprv.setObjectName("labelXprv")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelXprv)
        self.plainTextEditXprv = QtWidgets.QPlainTextEdit(dialogHdBackup)
        self.plainTextEditXprv.setReadOnly(True)
        self.plainTextEditXprv.setObjectName("plainTextEditXprv")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.plainTextEditXprv)
        self.labelXpub = QtWidgets.QLabel(dialogHdBackup)
        self.labelXpub.setObjectName("labelXpub")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelXpub)
        self.plainTextEditXpub = QtWidgets.QPlainTextEdit(dialogHdBackup)
        self.plainTextEditXpub.setReadOnly(True)
        self.plainTextEditXpub.setObjectName("plainTextEditXpub")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.plainTextEditXpub)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.pushButtonOk = QtWidgets.QPushButton(dialogHdBackup)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.gridLayout.addWidget(self.pushButtonOk, 1, 0, 1, 1)

        self.retranslateUi(dialogHdBackup)
        self.pushButtonOk.clicked.connect(dialogHdBackup.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialogHdBackup)

    def retranslateUi(self, dialogHdBackup):
        _translate = QtCore.QCoreApplication.translate
        dialogHdBackup.setWindowTitle(_translate("dialogHdBackup", "HD 钱包"))
        self.labelMnemonic.setText(_translate("dialogHdBackup", "助记词 (Mnemonic) ："))
        self.labelPath.setText(_translate("dialogHdBackup", "衍生路径 (Derivation Path) ："))
        self.labelPassphrase.setText(_translate("dialogHdBackup", "助记词密码 (Passphrase) ："))
        self.labelXprv.setText(_translate("dialogHdBackup", "扩展私钥 (Xprv) ："))
        self.labelXpub.setText(_translate("dialogHdBackup", "扩展公钥 (Xpub) ："))
        self.pushButtonOk.setText(_translate("dialogHdBackup", "确定"))
