# Form implementation generated from reading ui file 'input_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialogInput(object):
    def setupUi(self, dialogInput):
        dialogInput.setObjectName("dialogInput")
        dialogInput.resize(400, 140)
        self.gridLayout = QtWidgets.QGridLayout(dialogInput)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(dialogInput)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.labelDescription = QtWidgets.QLabel(dialogInput)
        self.labelDescription.setObjectName("labelDescription")
        self.gridLayout.addWidget(self.labelDescription, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(dialogInput)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(dialogInput)
        self.buttonBox.rejected.connect(dialogInput.reject) # type: ignore
        self.buttonBox.accepted.connect(dialogInput.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialogInput)

    def retranslateUi(self, dialogInput):
        _translate = QtCore.QCoreApplication.translate
        dialogInput.setWindowTitle(_translate("dialogInput", "标题"))
        self.labelDescription.setText(_translate("dialogInput", "描述。"))
