# Form implementation generated from reading ui file 'key.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialogKey(object):
    def setupUi(self, dialogKey):
        dialogKey.setObjectName("dialogKey")
        dialogKey.resize(600, 290)
        dialogKey.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.gridLayout = QtWidgets.QGridLayout(dialogKey)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.labelWif = QtWidgets.QLabel(parent=dialogKey)
        self.labelWif.setObjectName("labelWif")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelWif)
        self.lineEditWif = QtWidgets.QLineEdit(parent=dialogKey)
        self.lineEditWif.setText("")
        self.lineEditWif.setReadOnly(True)
        self.lineEditWif.setObjectName("lineEditWif")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditWif)
        self.labelKeyHex = QtWidgets.QLabel(parent=dialogKey)
        self.labelKeyHex.setObjectName("labelKeyHex")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelKeyHex)
        self.plainTextKeyHex = QtWidgets.QPlainTextEdit(parent=dialogKey)
        self.plainTextKeyHex.setReadOnly(True)
        self.plainTextKeyHex.setObjectName("plainTextKeyHex")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.plainTextKeyHex)
        self.labelPk = QtWidgets.QLabel(parent=dialogKey)
        self.labelPk.setObjectName("labelPk")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelPk)
        self.plainTextEditPk = QtWidgets.QPlainTextEdit(parent=dialogKey)
        self.plainTextEditPk.setReadOnly(True)
        self.plainTextEditPk.setObjectName("plainTextEditPk")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.plainTextEditPk)
        self.labelAddress = QtWidgets.QLabel(parent=dialogKey)
        self.labelAddress.setObjectName("labelAddress")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelAddress)
        self.lineEditAddress = QtWidgets.QLineEdit(parent=dialogKey)
        self.lineEditAddress.setReadOnly(True)
        self.lineEditAddress.setObjectName("lineEditAddress")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditAddress)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.pushButtonOk = QtWidgets.QPushButton(parent=dialogKey)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.gridLayout.addWidget(self.pushButtonOk, 1, 0, 1, 1)

        self.retranslateUi(dialogKey)
        self.pushButtonOk.clicked.connect(dialogKey.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialogKey)

    def retranslateUi(self, dialogKey):
        _translate = QtCore.QCoreApplication.translate
        dialogKey.setWindowTitle(_translate("dialogKey", "Key"))
        self.labelWif.setText(_translate("dialogKey", "Private Key (WIF) :"))
        self.labelKeyHex.setText(_translate("dialogKey", "Private Key (Hex) :"))
        self.labelPk.setText(_translate("dialogKey", "Public Key :"))
        self.labelAddress.setText(_translate("dialogKey", "Address :"))
        self.pushButtonOk.setText(_translate("dialogKey", "OK"))
