# Form implementation generated from reading ui file 'send_ft.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialogSendFt(object):
    def setupUi(self, dialogSendFt):
        dialogSendFt.setObjectName("dialogSendFt")
        dialogSendFt.resize(550, 300)
        dialogSendFt.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.gridLayout = QtWidgets.QGridLayout(dialogSendFt)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.labelReceivers = QtWidgets.QLabel(parent=dialogSendFt)
        self.labelReceivers.setObjectName("labelReceivers")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelReceivers)
        self.plainTextEditReceivers = QtWidgets.QPlainTextEdit(parent=dialogSendFt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEditReceivers.sizePolicy().hasHeightForWidth())
        self.plainTextEditReceivers.setSizePolicy(sizePolicy)
        self.plainTextEditReceivers.setObjectName("plainTextEditReceivers")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.plainTextEditReceivers)
        self.labelAmount = QtWidgets.QLabel(parent=dialogSendFt)
        self.labelAmount.setObjectName("labelAmount")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelAmount)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditAmount = QtWidgets.QLineEdit(parent=dialogSendFt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAmount.sizePolicy().hasHeightForWidth())
        self.lineEditAmount.setSizePolicy(sizePolicy)
        self.lineEditAmount.setPlaceholderText("")
        self.lineEditAmount.setObjectName("lineEditAmount")
        self.horizontalLayout.addWidget(self.lineEditAmount)
        self.labelFtSymbol = QtWidgets.QLabel(parent=dialogSendFt)
        self.labelFtSymbol.setObjectName("labelFtSymbol")
        self.horizontalLayout.addWidget(self.labelFtSymbol)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolButtonMaxAmount = QtWidgets.QToolButton(parent=dialogSendFt)
        self.toolButtonMaxAmount.setObjectName("toolButtonMaxAmount")
        self.horizontalLayout.addWidget(self.toolButtonMaxAmount)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 3)
        self.pushButtonSend = QtWidgets.QPushButton(parent=dialogSendFt)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.gridLayout.addWidget(self.pushButtonSend, 1, 1, 1, 1)

        self.retranslateUi(dialogSendFt)
        QtCore.QMetaObject.connectSlotsByName(dialogSendFt)

    def retranslateUi(self, dialogSendFt):
        _translate = QtCore.QCoreApplication.translate
        dialogSendFt.setWindowTitle(_translate("dialogSendFt", "Send"))
        self.labelReceivers.setText(_translate("dialogSendFt", "Receivers"))
        self.labelAmount.setText(_translate("dialogSendFt", "Send Amount"))
        self.labelFtSymbol.setText(_translate("dialogSendFt", "FT"))
        self.toolButtonMaxAmount.setText(_translate("dialogSendFt", "Max Amount"))
        self.pushButtonSend.setText(_translate("dialogSendFt", "Send"))
